In [2]:
import csv
import pandas as pd
import re
from pandas.core.frame import DataFrame

In [3]:
def display_csv_data(file_path, delimiter):
    csv_data = pd.read_csv(file_path, delimiter=delimiter)
    csv_data.shape
    return csv_data

# space-separeted
display_csv_data('log_tcp_complete', ' ')

,#15#c_ip:1,c_port:2,c_pkts_all:3,c_rst_cnt:4,c_ack_cnt:5,c_ack_cnt_p:6,c_bytes_uniq:7,c_pkts_data:8,c_bytes_all:9,c_pkts_retx:10,...,c_last_handshakeT:121,s_last_handshakeT:122,c_appdataT:123,s_appdataT:124,c_appdataB:125,s_appdataB:126,fqdn:127,dns_rslv:128,req_tm:129,res_tm:130
0,163.35.158.67,64548,17,0,16,9,714,6,714,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
1,163.35.93.53,57278,17,0,16,9,746,6,746,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
2,187.82.166.205,62903,11,0,10,7,2691,2,2691,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
3,163.35.139.166,59094,17,0,16,9,746,6,746,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
4,187.82.166.205,62904,10,1,8,6,256,1,256,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886462,163.35.158.2,57607,7,0,6,2,3546,3,3546,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
886463,163.35.158.2,57608,7,0,6,2,3546,3,3546,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
886464,163.35.93.244,58938,435,0,434,260,228163,173,229537,1,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
886465,59.44.95.176,47121,3,0,0,0,0,0,0,2,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0
886466,187.82.166.205,12876,9,0,8,6,213,1,213,0,...,0.0,0.0,0.0,0.0,0,0,-,-,0.0,0.0

In [4]:
# 1.2
def avg_calculator(file_path, column):
    data = pd.read_csv(file_path, delimiter=' ')
    avg = data.iloc[:, column].mean()
    print(avg)

cols = [3, 7, 10, 17, 21, 24]
for i in cols:
    avg_calculator('log_tcp_complete', i-1)

93.57308845112114
36741.18263285604
0.4918265428944337
178.71628047067742
214087.7370325122
2.2858978394006773

In [6]:
# 1.3
import numpy as np
data = pd.read_csv('log_tcp_complete', delimiter=' ')
cols = [10, 7]
thresholds = [0.01, 0.1, 0.2]
record_number = len(data)
for t in thresholds:
    exceed_case = 0
    for line in range(0, len(data)):
        a = data.iloc[line, cols[0]-1]
        b = data.iloc[line, cols[1]-1]
        # ignore the case when c7 = 0
        if b == 0:
            continue
        if a/b > t:
        #if np.true_divide(a,b) > t:
            exceed_case += 1
    percentage = exceed_case/record_number
    print(percentage)

0.017066625153559015
0.0049522430050977645
0.0030209810404673836

In [66]:
# 1.4
def largest_value(file_path, column):
    data = pd.read_csv(file_path, delimiter=' ')
    max_value = data.iloc[:,column].max()
    return max_value

cols = [3, 9, 17, 23, 31]
for i in cols:
    max_value = largest_value('log_tcp_complete', i-1)
    print(max_value)

1700014
313220528
2791706
3835783508
72901107.834